apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpbin
spec:
  selector:
    matchLabels:
      app: go-httpbin
  template:
    metadata:
      labels:
        app: go-httpbin
    spec:
      containers:
      - name: go-httpbin
        image: mccutchen/go-httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-httpbin
spec:
  selector:
    app: go-httpbin
  ports:
  - port: 8080
    targetPort: 8080
