apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deploy/app/go-httpbin.yaml
- ./deploy/flux-notifications/alert.yaml
- ./grafana/grafana-config.yaml
- ./grafana/grafana-k6.yaml
- ./grafana/grafana.yaml
- ./prometheus/prometheus.yaml
- ./prometheus/service-monitor.yaml
