apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  namespace: default
  labels:
    env: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator
  endpoints:
  - port: http

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: default
  labels:
    env: demo
spec:
  selector:
    matchLabels:
      managed-by: prometheus-operator
      operated-prometheus: "true"
  endpoints:
  - port: web
